sudo: false
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - binutils-gold
    - g++-4.9
    - gcc-4.9
    - git
    - debhelper
    - devscripts
    - python
    - python-software-properties
    - gnupg

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then export CXX=/usr/bin/g++-4.9;  export CC=/usr/bin/gcc-4.9; fi
  - if [ $TRAVIS_OS_NAME == 'osx' ]; then export CXX=g++;  export CC=gcc; fi
  - $CC --version
  - $CXX --version

before_script:
  # Perform a sanity check before proceeding
  - echo "no" | tools/packaging/cpt.py -c

script:
  # FIXME: Change URLs to the repo of @vgvassilev after repositories have been updated.
  # Remove --no-test option when appropriate.
  - tools/packaging/cpt.py --create-dev-env=release --no-test --with-llvm-url=http://root.cern.ch/git/llvm.git --with-clang-url=http://root.cern.ch/git/clang.git --with-cling-url=http://root.cern.ch/git/cling.git

branches:
  only:
    - master

notifications:
  recipients:
    - vvasilev@cern.ch
    - ani07nov@gmail.com
    #- cling-dev@cern.ch
  email:
    on_success: change
    on_failure: always

  template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
