language: cpp
sudo: false


os:
  - linux
  - osx


cache:
  ccache: true
  directories:
    - $HOME/.ccache
#    - $HOME/ci/build/cling-src
    - $TRAVIS_BUILD_DIR/deps

env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=500M
    - CCACHE_CPP2=1


matrix:
#  exclude:
#    - os: osx
#      compiler: gcc

  include:

  # 1. Linux Clang Builds

    - os: linux
      compiler: clang
      addons: &clang36
      apt:
        sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test']
        packages: ['clang-3.6']
      env: COMPILER='ccache clang++-3.6' BUILD_TYPE='Release'


  # 2. Linux GCC Builds

    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER='ccache g++-4.9' BUILD_TYPE='Release'

    - os: linux
      compiler: gcc
      addons: *gcc49
      env: COMPILER='ccache g++-4.9' BUILD_TYPE='Debug'

  # 3. OSX Clang Builds

    - os: osx
      compiler: clang
      osx_image: xcode7.2
      env: COMPILER='ccache clang++' BUILD_TYPE='Release'

  allow_failures:
    - os: osx

install:
# If cmake is not in the cache, download it.
- |
  if [ $TRAVIS_OS_NAME == 'linux' ]; then
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz"
    export CMAKE=$TRAVIS_BUILD_DIR/cmake/bin/cmake
  elif [ $TRAVIS_OS_NAME == 'osx' ] ; then
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Darwin-x86_64.tar.gz"
    export CMAKE=$TRAVIS_BUILD_DIR/cmake/CMake.app/Contents/bin/cmake
  fi

  if [ ! -f $CMAKE ]; then
    mkdir -pv $TRAVIS_BUILD_DIR/cmake
    travis_retry curl -k $CMAKE_URL | tar --strip-components=1 -xz -C $TRAVIS_BUILD_DIR/cmake
  fi

before_script:
- export CXX=${COMPILER}
- export
- which ccache
- $CMAKE --version
- $CC --version
- $CXX --version

script:
- |
  if [ -z $TRAVIS_TAG ]; then
    tools/packaging/cpt.py --current-dev=tar --with-cling-url=https://github.com/vgvassilev/cling --verbose
  else
    tools/packaging/cpt.py --last-stable=tar --with-cling-url=https://github.com/vgvassilev/cling
  fi
- ccache -s

notifications:
  recipients:
  - ani07nov@gmail.com
  - vvasilev@cern.ch
  email:
    on_success: change
    on_failure: always
  template:
  - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

before_deploy:
- export RELEASE_TARBALL=$(ls $HOME/ci/build/cling*.tar.bz2)
- echo "Deploying $RELEASE_TARBALL to GitHub releases"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eIwVHJNxkAIi6IUYyx7qI1szsgWt3c42ugcJ1vZ6iH//+qJgks77I8dMlbRf0RUrhxpJhJPH5a6vqI/mo1Vq2vmoC8+D1DIQCbj+/WHhY71LQCPC+Wgj2JES5y1Wh91nMt4ybzb1dA8BIfeJOdCUn7ezJTGKk18N+h2jE+a/7IE=
  file: '${RELEASE_TARBALL}'
  on:
    tags: true
    repo: vgvassilev/cling
