language: cpp

compiler:
- gcc
- clang

os:
- linux
- osx

matrix:
  exclude:
    - compiler: gcc
      os: osx

sudo: true

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - binutils-gold
      - g++-4.8
      - gcc-4.8
      - clang-3.6
    #alternatives: implemented 2 days ago and still to come.

before_install:
- echo $LANG
- echo $LC_ALL
- clang --version || gcc --version
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    if [ "$CXX" == "g++" ]; then
      export CXX=/usr/bin/g++-4.8;
      export CC=/usr/bin/gcc-4.8;
    elif [ "$CXX" == "clang++" ]; then
      export CXX=/usr/bin/clang++-3.6;
      export CC=/usr/bin/clang-3.6;
    fi
  fi
- export

before_script:
- mkdir src inst obj
- mkdir -v $TRAVIS_BUILD_DIR/tmp
- ls -l
- git clone https://github.com/vgvassilev/llvm.git src
- (cd src && git checkout cling-patches)
- git clone https://github.com/vgvassilev/clang.git src/tools/clang
- (cd src/tools/clang && git checkout cling-patches)
- git clone https://github.com/vgvassilev/cling.git src/tools/cling
- cd src
- cd ../obj
- travis_retry ../src/configure --prefix=`pwd`/../inst --disable-docs --disable-bindings
  --disable-visibility-inlines-hidden --disable-clang-rewriter --disable-clang-static-analyzer
  --disable-clang-arcmt --disable-compiler-version-checks --enable-targets=host --enable-optimized=yes

script:
- travis_retry make -j4 -k
- travis_retry make -j4 -k
- travis_retry make install
- cd tools/cling
- make test LIT_ARGS=--no-progress-bar

branches:
  only:
  - master

notifications:
  recipients:
  - v.g.vassilev@gmail.com
  email:
    on_success: change
    on_failure: always
  template:
  - '%{repository}/%{branch} (%{commit} - %{author}): %{message}'

deploy:
  provider: releases
  api_key:
    secure: avhabhfxtmQ/WM3yJw8MbmfzIurOqf7Y+Wx+Xa6jwrHqrVn6UpvZiZ7An+3ieTv6ohDw6EjtbcvZizrnqDtnLlDqsFmlynC92raE5YU9DceK1cfNEflohQ0d+EVRRFQ6Y52YwPQbJ78kj26DAdHVSl+9n95VNGI3lEsIaYcNZWo=
  file: ''
  on:
    tags: true
